name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip -DestinationPath ngrok
    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken 2nWtt8ljTb8UaRWAVOtxplMcrrx_2UvgPgf4hacnAqk9jAJoG
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create ngrok Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
    - name: Set up keep-alive
      run: |
        $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "Add-Content -Path 'C:\keepalive.txt' -Value 'Keep-Alive'"
        $trigger = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Minutes 5) -RepeatIndefinitely -At (Get-Date).Date.AddMinutes(1)
        $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -Hidden -RunOnlyIfNetworkAvailable
        Register-ScheduledTask -Action $action -Trigger $trigger -Settings $settings -TaskName "KeepAlive"
